name: RustDesk-RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download RustDesk Portable
        run: |
          $url="https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe"
          Invoke-WebRequest $url -OutFile rustdesk.exe

      - name: Start RustDesk
        run: |
          Start-Process ".\rustdesk.exe"
          Start-Sleep 15

      - name: Show RustDesk ID
        run: |
          .\rustdesk.exe --get-id

      - name: Keep Runner Alive
        run: |
          while ($true) {
            Write-Host "RustDesk Running..."
            Start-Sleep 300
          }
